apiVersion: v1
kind: Namespace
metadata:
  name: observability-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: observability-app
  name: observability-app
  namespace: observability-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observability-app
  strategy: {}
  template:
    metadata:
      labels:
        app: observability-app
    spec:
      containers:
      - image: 936068047509.dkr.ecr.us-east-1.amazonaws.com/observability-app:5
        name: observability-app
        ports:
        - containerPort: 5000
        env:
          # - name: AWS_XRAY_DAEMON_ADDRESS
          #   value: observability-collector.aws-otel-eks:2000
          - name: OTEL_EXPORTER
            value: otlp
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://observability-collector.aws-otel-eks.svc.cluster.local:55680
          - name: OTEL_SERVICE_NAME
            value: observability-app
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=observability-app"
          - name: OTEL_METRICS_EXPORTER
            value: ""
        resources: {}
