apiVersion: v1
kind: Namespace
metadata:
  name: flask-app-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app-1
  name: flask-app-1
  namespace: flask-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-1
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-app-1
    spec:
      containers:
      - image: __FLASK_APP_1_URI__
        name: flask-app-1
        ports:
        - containerPort: 5000
        env:
          # - name: AWS_XRAY_DAEMON_ADDRESS
          #   value: observability-collector.aws-otel-eks:2000
          - name: OTEL_EXPORTER
            value: otlp
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://observability-collector.monitoring.svc.cluster.local:55680
          - name: OTEL_SERVICE_NAME
            value: flask-app-1
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=flask-app-1"
          - name: OTEL_METRICS_EXPORTER
            value: ""
        resources: {}
