apiVersion: v1
kind: Service
metadata:
  labels:
    app: observability-app
  name: observability-app
  namespace: observability-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: observability-app
  type: LoadBalancer
