apiVersion: v1
kind: Namespace
metadata:
  name: flask-second
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-second
  name: flask-second
  namespace: flask-second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-second
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-second
    spec:
      containers:
      - image: 936068047509.dkr.ecr.us-east-2.amazonaws.com/flask-app-2:2
        name: flask-second
        ports:
        - containerPort: 5000
        env:
          # - name: AWS_XRAY_DAEMON_ADDRESS
          #   value: observability-collector.aws-otel-eks:2000
          - name: OTEL_EXPORTER
            value: otlp
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://observability-collector.monitoring.svc.cluster.local:55680
          - name: OTEL_SERVICE_NAME
            value: flask-second
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=flask-second"
          - name: OTEL_METRICS_EXPORTER
            value: ""
          - name: OTEL_PYTHON_LOG_CORRELATION
            value: "true"
        resources: {}
