apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-second
  name: flask-second
  namespace: flask-second
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-second
  type: LoadBalancer
